---
Common:
  ChipModel: WT0032
  OutputFolder: .\Output
  LogFolder: .\Log

TouchSimulation:
  LogFile: TouchSimulation.log

WT0014:
  FirmwarePath: U:\WeidaHiTech\TestData\WDT875X_Flash_512k_2020_0529_000.bin
  RawImagePath: U:\WeidaHiTech\TestData\WDT875X_ImageDump_2020_0519_002_jig.csv
  LogPath: TouchSimulation.log
  ImageWidth: 46
  ImageHeight: 22

WT0031:
  FirmwarePath: U:\WeidaHiTech\TestData\WDT8761AT_flash_508k_2020_0707_000.bin
  RawImagePath: U:\WeidaHiTech\TestData\WDT8761AT_ImageDump_2020_0707_000.csv
  LogPath: .\Log\FirmwareSimulator.log

WT0032:
  FirmwarePath: U:\WeidaHiTech\TestData\WDT8762A_flash_508k_2020_0925_000.bin
  RawImagePath: U:\WeidaHiTech\TestData\WDT8762A_ImageDump_2020_0925_000.csv
  LogPath: .\Log\FirmwareSimulator.log

KoreaShinNts:
  FirmwarePath: U:\WeidaHiTech\TestData\WDT8761AT_flash_508k_2020_0619_Shin.bin
  RawImagePath: U:\WeidaHiTech\TestData\WDT8761AT_ImageDump_2020_0619_Pos16.csv
  LogPath: .\Log\FirmwareSimulator.log
